# Generated by Django 5.0.6 on 2024-07-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
    ]
