# Generated by Django 5.0.6 on 2024-07-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
    ]
