# Generated by Django 5.0.6 on 2024-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Chevrolet', max_length=250),
        ),
    ]
